graph LR
    %% objects
    Position[[Position]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    RotationType[RotationType]
    ApplyRotationTranslation([ApplyRotationTranslation])
    Tetromino[[Tetromino]]
    TetrominoKind[TetrominoKind]

    subgraph spatial_primitives
        Direction ~~~ Position
    end

    subgraph rotation_translation
        RotationTranslation --o RotationType
    end

    RotationTranslation --o Position

    subgraph moving_primitives
        ApplyRotationTranslation
    end

    ApplyRotationTranslation ==> Position
    ApplyRotationTranslation ==> Direction
    ApplyRotationTranslation -.-> RotationTranslation

    Tetromino -.-> ApplyRotationTranslation

    subgraph tetromino_kind
        TetrominoKind
    end

    Tetromino --o spatial_primitives
    Tetromino --o TetrominoKind
