graph LR
    %% objects
    state0[default position and orientation]
    state2[valid position and orientation wrt. grid]
    ending[ ]

    state0 --"try_enter_grid(&mut self, &TetrisGrid)"--> state2
    subgraph g1[ ]
        state2 --"try_apply(&mut self, TetrominoMove, &TetrisGrid)"--> state2
    end
    state2 --"reset(&mut self)"--> state0
    state2 --"lock_down(self, &mut TetrisGrid)"--> ending

    style ending stroke: none, fill:none;
    style g1 stroke:none, fill:none;
