[workspace]
resolver = "3"
members = ["tetris", "tetris_core", "render_tetris"]

[workspace.dependencies]
piston_window = "0.132.0"
piston = { version = "1.0.0", features = ["async"] }
piston2d-graphics = "0.44.0"
piston2d-opengl_graphics = "0.85.0"
rand = "0.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"
rand_pcg = "0.10.0"
local-ip-address = "0.6.3"
arboard = "3.4.1"
include_assets = { git = "https://github.com/william-gooch/include_assets" }
simple-mermaid = "0.2.0"
rstest = "0.26.1"
pistoncore-glfw_window = { git = "https://github.com/PistonDevelopers/glfw_window" }
