graph LR
    %% objects
    TetrominoMove[TetrominoMove]
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    TetrisResult[TetrisResult]
    Tetromino[[Tetromino]]
    Position[[Position]]
    TetrisColor[TetrisColor]
    TetrominoGenerator[[TetrominoGenerator]]
    BagType[BagType]
    CircularBuffer[[CircularBuffer]]
    TetrisPlayer[[TetrisPlayer]]

    subgraph tetris_player
        TetrisPlayer
    end
    TetrisPlayer --o TetrisGrid
    TetrisPlayer --o Tetromino
    TetrisPlayer --o CircularBuffer
    TetrisPlayer -.-> TetrominoGenerator

    subgraph tetromino_generator
        TetrominoGenerator --o BagType
    end
    TetrominoGenerator
    TetrominoGenerator -.-> Tetromino

    subgraph circular_buffer
        CircularBuffer
    end

    subgraph tetris_grid
        direction LR
        TetrisGrid -.-> GameOverError
        TetrisGrid -.-> TetrisResult
        TetrisResult --o GameOverError
        TetrisGrid --o TetrisColor
    end
    Tetromino -.-> tetris_grid
    TetrisGrid -.-> Position

    subgraph tetromino
        Tetromino --o Position
        TetrominoMove -.-> Position
        Tetromino -.-> TetrominoMove
    end

    style TetrisResult stroke-dasharray: 5 5;
