graph LR
    %% objects
    TetrominoMove[TetrominoMove]
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    Tetromino[[Tetromino]]
    Position[[Position]]
    TetrominoKind[TetrominoKind]
    TetrisColor[TetrisColor]
    TetrominoGenerator[[TetrominoGenerator]]

    subgraph tetromino_generator
        TetrominoGenerator
    end
    TetrominoGenerator --o TetrominoKind

    subgraph tetromino
        Tetromino --o TetrominoKind
        Tetromino --o Position
    end

    subgraph tetromino_move
        TetrominoMove
    end

    subgraph tetris_grid
        direction LR
        TetrisGrid -.-> GameOverError
        TetrisGrid --o TetrisColor
    end

    Tetromino -.-> tetris_grid
