graph LR
    %% objects
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    TetrisColor[TetrisColor]
    Position[[Position]]

    subgraph tetromino
        TetrominoKind
        Position
    end

    subgraph tetris_grid
        TetrisGrid --o TetrisColor
        TetrisGrid -.-> GameOverError
        TetrisGrid -.-> Position
        TetrisColor -.-> TetrominoKind
    end

