graph LR
    %% objects
    TetrominoMove[TetrominoMove]
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    TetrisResult[TetrisResult]
    Tetromino[[Tetromino]]
    Position[[Position]]
    TetrisColor[TetrisColor]
    TetrominoGenerator[[TetrominoGenerator]]
    BagType[BagType]
    CircularArray[[CircularArray]]

    subgraph tetromino_generator
        TetrominoGenerator --o BagType
    end
    TetrominoGenerator
    TetrominoGenerator -.-> Tetromino

    subgraph circular_array
        CircularArray
    end

    subgraph tetromino
        Tetromino --o Position
        TetrominoMove -.-> Position
        Tetromino -.-> TetrominoMove
    end

    subgraph tetris_grid
        direction LR
        TetrisGrid -.-> GameOverError
        TetrisGrid -.-> TetrisResult
        TetrisResult --o GameOverError
        TetrisGrid --o TetrisColor
    end

    Tetromino -.-> tetris_grid
    TetrisGrid -.-> Position

    style TetrisResult stroke-dasharray: 5 5;
