graph LR
    %% objects
    TetrominoMove[TetrominoMove]
    Position[[Position]]
    RotationType[RotationType]

    subgraph tetromino
        Position
        RotationType
    end

    TetrominoMove -.-> Position
    TetrominoMove -.-> RotationType
