graph LR
    %% objects
    Position[[Position]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    RotationType[RotationType]
    ApplyRotationTranslation([ApplyRotationTranslation])
    Block[[Block]]
    TryMoveBlock([TryMoveBlock])
    TetrisGrid[[TetrisGrid]]
    Tetromino[[Tetromino]]
    UseTetromino([UseTetromino])

    %% modules
    spatial_primitives[spatial_primitives]
    rotation_translation[rotation_translation]
    moving_primitives[moving_primitives]
    tetromino[tetromino]

    subgraph spatial_primitives
        Direction ~~~ Position
    end
    

    subgraph rotation_translation
        RotationTranslation --o RotationType
    end

    RotationTranslation --o Position

    subgraph moving_primitives
        ApplyRotationTranslation
    end

    ApplyRotationTranslation ==> Position & Direction
    ApplyRotationTranslation -.-> RotationTranslation
    
    subgraph tetris_block
        TryMoveBlock ==> Block
    end

    subgraph tetris_grid
        TetrisGrid
    end

    Block -.-> ApplyRotationTranslation & TetrisGrid

    subgraph tetromino
        UseTetromino ==> Tetromino
    end

    Tetromino --o spatial_primitives & Block
    Tetromino -.-> ApplyRotationTranslation & TryMoveBlock