graph LR
    %% objects
    Position[[Position]]
    Block[[Block]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    ApplyRotationTranslation([ApplyRotationTranslation])
    ZoomInAndOut([ZoomInAndOut])

    %% modules
    rotation_translation[rotation_translation]
    spatial_primitives[spatial_primitives]
    moving_primitives[moving_primitives]

    subgraph spatial_primitives
        Block --o Position
        Direction
    end

    subgraph rotation_translation
        RotationTranslation
    end

    subgraph moving_primitives
        ApplyRotationTranslation
        ZoomInAndOut
    end

    ZoomInAndOut === Position
    ApplyRotationTranslation === Position & Block & Direction
    ApplyRotationTranslation -.-> RotationTranslation
    ApplyRotationTranslation -.-> ZoomInAndOut

    ZoomInAndOut ~~~ Block & Direction & RotationTranslation