graph LR
    %% objects
    ending[ ]
    state0[default state]
    state1[starting position]
    state2[valid state wrt. grid]
    state2b@{ shape: text, label: "try_apply(&mut self, TetrominoMove, &TetrisGrid)" }

    state2 --"reset(&mut self)"--> state0
    state0 --"enter_grid(&mut self, &TetrisGrid)"--> state1
    state1 --"is_valid_in_grid(&self, &TetrisGrid)"--> state2
    state2 --- state2b
    state2b --> state2
    state2b ~~~ ending
    state2 --"lock_down(self, &mut TetrisGrid)"--> ending


    style ending stroke: none, fill:none;
    style state2b fill:none;
    style state2b stroke:transparent,fill:#585858;
