graph LR
    %% objects
    BagType[BagType]
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    TetrisResult[TetrisResult]
    Tetromino[[Tetromino]]
    Position[[Position]]
    TetrisColor[TetrisColor]
    TetrisPlayer[[TetrisPlayer]]
    MockRng[[MockRng]]
    TetrisCommand[TetrisCommand]
    TetrominoKind[TetrominoKind]
    RenderTetrisPlayer([RenderTetrisPlayer])
    CircularBuffer[[CircularBuffer]]
    TetrisGridCreationError[TetrisGridCreationError]

    RenderTetrisPlayer -.-> CircularBuffer

    TetrisPlayer
    MockRng
    RenderTetrisPlayer

    TetrisPlayer --o Tetromino
    RenderTetrisPlayer -.-> Tetromino

    subgraph tetromino[" "]
        Tetromino --o Position
        Tetromino --o TetrominoKind
    end


    subgraph tetris_grid[" "]
        TetrisGrid --o TetrisColor
        TetrisGrid -.-> TetrisGridCreationError
        TetrisGrid -.-> TetrisResult
        TetrisResult --o GameOverError
        TetrisGrid -.-> GameOverError
    end

    RenderTetrisPlayer -.-> TetrisGrid
    TetrisPlayer --o TetrisGrid
    TetrisPlayer --o BagType

    
    style TetrisResult stroke-dasharray: 5 5;
