graph LR
    %% objects
    BagType[BagType]
    TetrisGrid[[TetrisGrid]]
    GameOverError[GameOverError]
    TetrisResult[TetrisResult]
    Tetromino[[Tetromino]]
    Position[[Position]]
    TetrisColor[TetrisColor]
    TetrisPlayer[[TetrisPlayer]]
    TetrisCommand[TetrisCommand]
    TetrominoKind[TetrominoKind]
    MockRng[[MockRng]]
    TetrominoMove[TetrominoMove]

    subgraph tetris_player
        TetrisPlayer
        TetrisCommand
    end
    TetrisPlayer --o TetrisGrid
    TetrisPlayer --o Tetromino
    TetrisPlayer --o BagType

    subgraph mock_rng
        MockRng
    end
    MockRng -.-> TetrominoKind
    Tetromino -.-> tetris_grid
    TetrisGrid -.-> Position


    subgraph tetromino
        Tetromino --o Position
        Tetromino --o TetrominoKind
        TetrominoMove
    end
    TetrisCommand --o TetrominoMove

    subgraph tetromino_generator
        BagType
    end

    subgraph tetris_grid
        TetrisGrid -.-> GameOverError
        TetrisGrid -.-> TetrisResult
        TetrisResult --o GameOverError
        TetrisGrid --o TetrisColor
    end

    style TetrisResult stroke-dasharray: 5 5;
