graph LR
    %% objects
    TetrisPlayer[[TetrisPlayer]]

    TetrisGrid[[TetrisGrid]]
    TetrisColor[TetrisColor]
    GameOverError[GameOverError]
    TetrisGridCreationError[TetrisGridCreationError]

    BagType[BagType]
    CircularBuffer[[CircularBuffer]]
    Tetromino[[Tetromino]]
    TetrominoKind[TetrominoKind]
    Position[[Position]]

    TetrisCommand[TetrisCommand]
    LineClear[LineClear]
    MockRng[[MockRng]]


    TetrisPlayer -.-> TetrisCommand
    TetrisPlayer -.-> MockRng
    TetrisPlayer -.-> LineClear

    TetrisPlayer ---o TetrisGrid
    %% subgraph tetris_grid[" "]
        TetrisGrid --o TetrisColor
        TetrisGrid -.-> GameOverError
        TetrisGrid -.-> TetrisGridCreationError
    %% end

    TetrisPlayer ---o CircularBuffer
    TetrisPlayer ---o BagType

    TetrisPlayer ---o Tetromino
    %% subgraph tetromino[" "]
        Tetromino --o TetrominoKind
        Tetromino --o Position
    %% end
