graph LR
    %% objects
    TetrisPlayer::apply_player_move(TetrisPlayer::apply_player_move)
    TetrisCommand[TetrisCommand]
    MockRng[[MockRng]]
    LineClear[LineClear]
    GameOverError[GameOverError]

    subgraph Usage
        direction LR
        TetrisCommand --> TetrisPlayer::apply_player_move
        MockRng --> TetrisPlayer::apply_player_move
        TetrisPlayer::apply_player_move --> LineClear
        TetrisPlayer::apply_player_move -.-> GameOverError
    end

