graph LR
    %% objects
    BagType[BagType]
    TetrominoGenerator[[TetrominoGenerator]]
    Tetromino[[Tetromino]]

    subgraph tetromino
        Tetromino --o TetrominoKind
    end

    TetrominoGenerator --o BagType
    TetrominoGenerator --o TetrominoKind
    TetrominoGenerator -.-> Tetromino
