graph LR
    %% objects
    Position[[Position]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    RotationType[RotationType]
    ApplyRotationTranslation([ApplyRotationTranslation])
    %% TetrisGrid[[TetrisGrid]]
    Tetromino[[Tetromino]]
    %% GameOverError[GameOverError]
    TetrominoKind[TetrominoKind]

    subgraph spatial_primitives
        Direction ~~~ Position
    end

    subgraph rotation_translation
        RotationTranslation --o RotationType
    end

    RotationTranslation --o Position

    subgraph moving_primitives
        ApplyRotationTranslation
    end

    ApplyRotationTranslation ==> Position & Direction
    ApplyRotationTranslation -.-> RotationTranslation

    subgraph tetromino
        Tetromino
    end

    Tetromino -.-> ApplyRotationTranslation

    subgraph tetromino_kind
        TetrominoKind
    end

    %% subgraph tetris_grid
    %%     TetrisGrid
    %%     GameOverError
    %% end

    %% Tetromino ~~~ tetris_grid
    Tetromino --o spatial_primitives & TetrominoKind