graph LR
    %% objects
    Position[[Position]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    RotationType[RotationType]
    ApplyRotationTranslation([ApplyRotationTranslation])
    TetrisGrid[[TetrisGrid]]
    Tetromino[[Tetromino]]
    UseTetromino([UseTetromino])
    GameOverError[GameOverError]
    TetrominoKind[TetrominoKind]

    %% modules
    spatial_primitives[spatial_primitives]
    rotation_translation[rotation_translation]
    moving_primitives[moving_primitives]
    tetromino[tetromino]
    tetromino_kind[tetromino_kind]

    subgraph spatial_primitives
        Direction ~~~ Position
    end

    subgraph rotation_translation
        RotationTranslation --o RotationType
    end

    RotationTranslation --o Position

    subgraph moving_primitives
        ApplyRotationTranslation
    end

    ApplyRotationTranslation ==> Position & Direction
    ApplyRotationTranslation -.-> RotationTranslation

    subgraph tetromino
        UseTetromino ==> Tetromino
    end

    Tetromino -.-> ApplyRotationTranslation

    subgraph tetromino_kind
        TetrominoKind
    end

    subgraph tetris_grid
        TetrisGrid
        GameOverError
    end

    Tetromino ~~~ tetris_grid

    UseTetromino -.-> tetris_grid & TetrominoKind
    Tetromino --o spatial_primitives & TetrominoKind