graph LR
    %% objects
    Position[[Position]]
    Direction[Direction]
    RotationTranslation[[RotationTranslation]]
    ApplyRotationTranslation([ApplyRotationTranslation])
    ZoomInAndOut([ZoomInAndOut])

    %% modules
    rotation_translation[rotation_translation]
    spatial_primitives[spatial_primitives]
    moving_primitives[moving_primitives]

    subgraph spatial_primitives
        Direction
        Position
    end

    subgraph rotation_translation
        RotationTranslation
    end

    subgraph moving_primitives
        ApplyRotationTranslation
        ZoomInAndOut
    end

    ApplyRotationTranslation -.-> RotationTranslation
    ApplyRotationTranslation ==> Direction
    ApplyRotationTranslation === ZoomInAndOut
    ZoomInAndOut ==> Position

    ZoomInAndOut ~~~ Direction