graph LR
    %% objects
    is_block_empty(is_block_empty)
    is_in_grid(is_in_grid)
    is_above_skyline(is_above_skyline)
    add_block(add_block)
    clear_lines(clear_lines)
    is_block_available(is_block_available)
    can_blocks_spawn_on(can_blocks_spawn_on)
    add_blocks(add_blocks)
    apply(apply)
    can_enter_grid(can_enter_grid)
    lock_down(lock_down)
    new(new, reset)
    get_initial_position(get_initial_position)

    %% modules
    tetris_grid[tetris_grid]
    tetromino[tetromino]
    tetromino_kind[tetromino_kind]

    subgraph tetris_grid
        can_blocks_spawn_on -.-> is_block_empty
        is_block_available -.-> is_in_grid & is_block_empty
        add_blocks -.-> add_block & clear_lines & is_above_skyline
    end

    subgraph tetromino_kind
        get_initial_position
    end

    subgraph tetromino
        new & can_enter_grid & apply & lock_down
    end

    new -.-> get_initial_position
    can_enter_grid -.-> can_blocks_spawn_on
    apply -.-> is_block_available
    lock_down -.-> add_blocks